name: VoiceBox
main: com.kraken.voicebox.VoiceBox
version: 0.2.2 (alpha)
commands: 
     vb:
        description: Info for the VoiceBox chat plugin.
        usage: /<command>
     clearChat:
        description: Clears chat.
        usage: /<command>
     re:
        description: Reply publicly to a close (< 20m away) player.
        usage: /<command> <name> <msg>
     w:
        description: Whisper privately to a nearby (< 5m away) player.
        usage: /<command> <name> <msg>
     y:
        description: Yell loudly to all who can hear you (< 126m away).
        usage: /<command> <msg>