name: VoiceBox
main: com.kraken.voicebox.VoiceBox
version: 0.6.2 (beta)
commands: 
     vb:
        description: Info for the VoiceBox chat plugin.
        usage: /<command> {motd} {msg}
        aliases: [voicebox]
     clearChat:
        description: Clears chat.
        usage: /<command>
        aliases: [clearchat]
     re:
        description: Reply publicly to a close (< 20m away) player.
        usage: /<command> <name> <msg>
        aliases: [reply, respond]
     w:
        description: Whisper privately to a nearby (< 5m away) player.
        usage: /<command> <name> <msg>
        aliases: [whisper, tell]
     y:
        description: Yell loudly to all who can hear you (< 126m away).
        usage: /<command> <msg>
        aliases: [yell, shout]
     radio:
        description: Commands for radios.
        usage: /<command>
     ch:
        description: Set your radio's frequency.
        usage: /<command> <frequency>
        aliases: [channel, frequency, freq, tune]
     grumble:
        description: Grumble jibberish to close (< 20m away) players.
        usage: /<command>
     censor:
        description: Adjust the censor of blacklisted chat phrases.
        usage: /<command> <add/remove> <phrase>
     quote:
        description: Get a random quote, or add a quote.
        usage: /<command> {author} {quote}
        aliases: [quotes]
     joinMsg:
        description: Enable/disable player join messages.
        usage: /<command> <on/off>
        aliases: [joinmsg, joinMessage, joinmessage]